Repository NOW-SOPT-CDSP-TEAM-WEB4/Notefolio-Server, pull requests merged in 2024-05, with the labels that each got.

#3 [feat] 엔티티 구현
  notefolio/src/main/java/com/cdspseminar/notefolio/domain/Creative.java
  notefolio/src/main/java/com/cdspseminar/notefolio/domain/Creator.java
  notefolio/src/main/java/com/cdspseminar/notefolio/domain/Heart.java
  notefolio/src/main/java/com/cdspseminar/notefolio/domain/Program.java
  notefolio/src/main/java/com/cdspseminar/notefolio/domain/Workshop.java
  notefolio/src/main/java/com/cdspseminar/notefolio/domain/test.txt
Labels: 정원

#10 [feat] 워크샵 조회 API 구현
  notefolio/src/main/java/com/cdspseminar/notefolio/controller/WorkshopController.java
  notefolio/src/main/java/com/cdspseminar/notefolio/controller/test.txt
  notefolio/src/main/java/com/cdspseminar/notefolio/domain/Creator.java
  notefolio/src/main/java/com/cdspseminar/notefolio/dto/response/WorkshopGetResponse.java
  notefolio/src/main/java/com/cdspseminar/notefolio/dto/response/WorkshopsGetResponse.java
  notefolio/src/main/java/com/cdspseminar/notefolio/dto/response/test.txt
  notefolio/src/main/java/com/cdspseminar/notefolio/repository/WorkshopRepository.java
  notefolio/src/main/java/com/cdspseminar/notefolio/repository/test.txt
  notefolio/src/main/java/com/cdspseminar/notefolio/service/WorkshopService.java
  notefolio/src/main/java/com/cdspseminar/notefolio/service/test.txt
Labels: fix, 정원, feat

#9 [feat] 프로그램 전체 조회 API 구현
  notefolio/src/main/java/com/cdspseminar/notefolio/common/exception/ErrorStatus.java
  notefolio/src/main/java/com/cdspseminar/notefolio/controller/ProgramController.java
  notefolio/src/main/java/com/cdspseminar/notefolio/domain/Program.java
  notefolio/src/main/java/com/cdspseminar/notefolio/dto/response/ProgramsFindResponse.java
  notefolio/src/main/java/com/cdspseminar/notefolio/repository/ProgramRepository.java
  notefolio/src/main/java/com/cdspseminar/notefolio/service/ProgramService.java
Labels: 예린, feat

#12 [feat] 크리에이티브 검색 API 구현
  notefolio/src/main/java/com/cdspseminar/notefolio/controller/CreativeController.java
  notefolio/src/main/java/com/cdspseminar/notefolio/domain/Creative.java
  notefolio/src/main/java/com/cdspseminar/notefolio/domain/Creator.java
  notefolio/src/main/java/com/cdspseminar/notefolio/dto/response/CreativeGetResponse.java
  notefolio/src/main/java/com/cdspseminar/notefolio/dto/response/CreativesGetResponse.java
  notefolio/src/main/java/com/cdspseminar/notefolio/repository/CreativeRepository.java
  notefolio/src/main/java/com/cdspseminar/notefolio/service/CreativeService.java
Labels: 정원, feat

#15 [chore] WebConfig 설정 (#6)
  notefolio/src/main/java/com/cdspseminar/notefolio/config/WebConfig.java
Labels: fix, 정원

#18 [fix] numLike 수정
  notefolio/src/main/java/com/cdspseminar/notefolio/domain/Creative.java
Labels: 예린, fix

#20 [fix] 리스트 반환 개수 제한 구현
  notefolio/src/main/java/com/cdspseminar/notefolio/config/WebConfig.java
  notefolio/src/main/java/com/cdspseminar/notefolio/domain/Program.java
  notefolio/src/main/java/com/cdspseminar/notefolio/service/CreativeService.java
  notefolio/src/main/java/com/cdspseminar/notefolio/service/ProgramService.java
  notefolio/src/main/java/com/cdspseminar/notefolio/service/WorkshopService.java
Labels: fix, 정원

#23 [fix] 좋아요 중복 예외처리
  notefolio/src/main/java/com/cdspseminar/notefolio/common/exception/ErrorStatus.java
  notefolio/src/main/java/com/cdspseminar/notefolio/controller/HeartController.java
  notefolio/src/main/java/com/cdspseminar/notefolio/repository/HeartRepository.java
  notefolio/src/main/java/com/cdspseminar/notefolio/service/HeartService.java
Labels: fix, 정원

#24 Feat/#22
  notefolio/src/main/java/com/cdspseminar/notefolio/dto/response/CreativeGetResponse.java
  notefolio/src/main/java/com/cdspseminar/notefolio/dto/response/CreativesGetResponse.java
  notefolio/src/main/java/com/cdspseminar/notefolio/dto/response/WorkshopGetResponse.java
  notefolio/src/main/java/com/cdspseminar/notefolio/dto/response/WorkshopsGetResponse.java
  notefolio/src/main/java/com/cdspseminar/notefolio/repository/CreativeRepository.java
  notefolio/src/main/java/com/cdspseminar/notefolio/service/CreativeService.java
Labels: 정원, feat
